CREATE TABLE IF NOT EXISTS statistics (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  app VARCHAR(255) NOT NULL,
  uri VARCHAR(255) NOT NULL,
  ip VARCHAR(255) NOT NULL,
  date TIMESTAMP NOT NULL
);